---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
    exclude_paths:
      - spec/
  rubocop:
    enabled: true
  reek:
    enabled: true
    exclude_paths:
      - spec/
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
  - tmp/
