---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - spec/
    config:
      languages:
        ruby:
          mass_threshold: 30
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
  - tmp/
  - spec/fixtures/
