---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
  - tmp/
