sudo: false
language: ruby
rvm:
  - 2.3.1

notifications:
  email: false

addons:
  code_climate:
    repo_token: 1b705fb5cd2bfbc456a02d3acf64494b9363ffca79ed22690b96c49546cd35c6

cache:
  - bundler

before_install:
  - gem install bundler -v 1.17.3
  - bundle _1.17.3_ install --jobs=3 --retry=3 --path=vendor/bundle
script:
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
