sudo: false
language: ruby
rvm:
  - 2.3.1

notifications:
  email: false

addons:
  code_climate:
    repo_token: ad743cd1c267d4a84bfa620869f906a68efba51baa3aadc0638b88330ce3ab3a

cache:
  - bundler

before_install:
  - gem install bundler -v 1.17.3
  - bundle _1.17.3_ install --jobs=3 --retry=3 --path=vendor/bundle
script:
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
