os: linux
dist: xenial
language: ruby
rvm:
  - 2.6.5
notifications:
  email: false
before_install:
  - gem install bundler -v 2.1.4
  - bundle config gems.distribusion.com $GEMSERVER_USER:$GEMSERVER_PASSWORD
  - bundle config rubygems.distribusion.com $RUBYGEMS_TOKEN
before_script:
  - cp .env.example .env
  - if [ ! -f ./vendor/cc-test-reporter ]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./vendor/cc-test-reporter;
    chmod +x ./vendor/cc-test-reporter;
    fi
script:
  - bundle exec rake
after_success:
  - ./vendor/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
