sudo: false
language: ruby
rvm:
  - 2.3.1

notifications:
  email: false

addons:
  code_climate:
    repo_token: eb758a7a8b04369f929aa1b962bc9764b6517539971b785600065cf5ad93e282

cache:
  - bundler

before_install: gem install bundler -v 1.13.7
script:
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
